### PR TITLE
Addition of status icon

### PR DESCRIPTION
**Pull request by burnsra**
screen shot 2016-08-16 at 9 27 08 pm

### CODE REVIEW

**Comment by zhuhaow** [comment]
Wow, that's amazing. Thanks.

**Comment by burnsra** [comment]
Thanks, great project!

**Comment by zhuhaow** [comment]
Hi @burnsra, I know it has been some time, but do you mind to sign this short [contributor license agreement](https://cla-assistant.io/zhuhaow/SpechtLite)?

This guarantees that I could relicense the project with a more permissive one (maybe a non-copyleft one) sometime later.

**Comment by burnsra** [comment]
Signed!

**Comment by zhuhaow** [comment]
Thank you!

2016年9月8日 +0800 20:05 Robert Burns <notifications@github.com>，写道：

**Pull request merged**
